### ISSUE TITLE
Broken link to this repo.

### ISSUE THREAD

**Issue by alidaf** [gbiggs/flexiport#7]
The link from http://gbiggs.github.io/hokuyoaist/#examples is broken - it links to gi**b**hub rather than gi**t**hub. I can't find a way to report to from the actual site so I've reported it here.

**Comment by gbiggs** [comment]
Fixed by https://github.com/gbiggs/hokuyoaist/commit/354779f57ba7218a57a6c1bac02185da18fa932b
